#!/usr/bin/php -dphar.readonly=0
<?php
$srcRoot = realpath(__DIR__."/vendor");
$buildRoot = realpath(__DIR__);
$iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($srcRoot, FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::LEAVES_ONLY);
echo "Build Symfony Console phar\n";
$phar = new Phar($buildRoot.'/benchmark.phar', 0, 'benchmark.phar');
$phar->buildFromIterator($iterator, $srcRoot);
$phar->addFile('benchmark');
$phar->setStub($phar->createDefaultStub("benchmark"));
exit("Build complete\n");
